version: "3.8"

services:
  calculadora-metabolica:
    image: calculadora-metabolica:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calculadora-metabolica-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Adicione estas linhas se precisar de variáveis de ambiente
    # env_file:
    #   - .env.production
